# Site settings
title: Nobe McGill
email: derek.yu.lind@gmail.com
description: > # http://nobe.mcgilleus.ca/index.html replacement
baseurl: "" # the subpath of your site, e.g. /blog/
url: "localhost:4000" # the base hostname & protocol for your site
twitter_username: cloudsInfinity
github_username:  DerekYu177

# Build settings
markdown: kramdown
include: ["_pages"]
