# Site Settings
title: Static Site
email: derek.yu.lind@gmail.com
description: >
  A guide to getting started with Jekyll.
baseurl: ""
url: "http://localhost:4000"
github_username:  DerekYu177
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
